# Generated by Django 5.2.1 on 2025-06-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное название команды или компании.",
                        max_length=128,
                        unique=True,
                        verbose_name="Название команды",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код для присоединения к команде.",
                        max_length=32,
                        unique=True,
                        verbose_name="Код приглашения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="appuser",
            name="status",
            field=models.CharField(
                choices=[("member", "Участник"), ("admin", "Администратор")],
                default="member",
                help_text="Роль пользователя в команде (участник или администратор).",
                max_length=16,
                verbose_name="Статус доступа",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Команда, к которой принадлежит пользователь.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.team",
                verbose_name="Команда",
            ),
        ),
    ]
