# Generated by Django 5.2.1 on 2025-06-25 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgstructure", "0001_initial"),
        ("users", "0002_team_alter_appuser_options_appuser_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Руководитель пользователя в оргструктуре.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="organizational_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Подразделение, к которому принадлежит пользователь.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="orgstructure.organizationalunit",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="unit_role",
            field=models.CharField(
                blank=True,
                help_text="Должность или роль пользователя в подразделении.",
                max_length=64,
                verbose_name="Роль в подразделении",
            ),
        ),
    ]
